version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Running linting and unit tests..."
      - npm run lint
      - npm test
  build:
    commands:
      - echo Building the application...
      - npm run build
artifacts:
  files:
    - '**/*'
  discard-paths: yes
