version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Specify the Node.js version
    commands:
      - echo "Installing Node.js dependencies..."
      - npm install  # Use `npm ci` for a clean install from package-lock.json
  pre_build:
    commands:
      - echo "Running linting and unit tests..."
      - npm test
  build:
    commands:
      - echo "Building the application..."
      - npm run build
artifacts:
  files:
    - '**/*'
  discard-paths: yes
cache:
  paths:
    - 'node_modules/**/*'
